### ISSUE TITLE
Bank01 not found

### ISSUE THREAD

**Issue by PlaystationtheCollectorsClub** [fgsfdsfgs/rawpsx#1]
Hi,
start makeiso get the error " bank01 is missing", but this file is in the Data folder (like the other bankxx files from the dos release), what is my fail on this?
Could you please help me, i would love to play the fullgame on my playstation 1.

**Comment by fgsfdsfgs** [comment]
It might be case sensitive, i.e. they might need to be renamed to `bank01` instead of `BANK01`.

**Comment by PlaystationtheCollectorsClub** [comment]
i tried to rename it in bank01, but get the same error =/
May i ask if you have the full build?, i think iam to dully to get this work, iam not a programmer, only gamer.

**Comment by fgsfdsfgs** [comment]
Better give me screenshots of the folder where makeiso.bat is and the data folder, as well as the exact messages you get when it fails.

**Comment by PlaystationtheCollectorsClub** [comment]
Sure =)
![github](https://user-images.githubusercontent.com/95545688/152658640-54a82efb-9d67-498c-b9ea-5c3c3910452e.jpg)

**Comment by fgsfdsfgs** [comment]
It looks like this is due to a breaking change in mkpsxiso. You can either try using the older version available [here](https://github.com/Lameguy64/mkpsxiso/releases/tag/v1.26) or open iso.xml with Notepad and change `srcdir` to `source`.

**Comment by PlaystationtheCollectorsClub** [comment]
Hi Buddy, i get it done!
i opend the iso.xml and see that there was some bankxx files are missing and edit the data folder, than take makiso 1.26 and it worked =)
Next issue is, the password screen on the main menu doesnt work and ingame with "start than select" it freeze the ps1(real hardware and duckstation)

**Comment by fgsfdsfgs** [comment]
That sounds like you're missing some bank files (possibly bank08 or bank09?) or they're from the wrong version. Make sure all of the files come from the same full DOS version of the game.

**Comment by PlaystationtheCollectorsClub** [comment]
Thanks you are right, i had the wrong wrong full version.
Thank you very much for your help and big thanks for this port, its awesome!
I hope someday there will be a Wolfenstein 3D Port from your for the ps1 =)
